apiVersion: v1
kind: Service
metadata:
  name: mariadb-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pv179.mariadb.dyn.cloud.e-infra.cz
    metallb.universe.tf/allow-shared-ip: "mariadb-lb-0583a2a2-0d28-4377-b6e1-34b3f06dd41e"
    metallb.universe.tf/address-pool: privmuni
spec:
  type: LoadBalancer
  # sessionAffinity: ClientIP
  ports:
  - name: mariadb-port
    port: 3306
    targetPort: 3306
  selector:
    app: mariadb
  loadBalancerSourceRanges:
  - 147.251.0.0/16
  - 100.64.0.0/10
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 10.0.0.0/8